describe('Check gift subscription', () => {
    beforeEach(() => {
        cy.visit('/gift')
    })

    it('Check 12 months subscription scenario', () => {
        cy.get('#mainContent')
            .find('div.flex.flex-wrap._9hcI9q > div:nth-child(1)')
            .find('button > span')
            .click()
        cy.get('#trapfocus_6')
            .find('div.ml-36').as('commonForm')    
        cy.get('@commonForm')
            .should('contain.text', 'Ready to wrap it up?')
            .should('contain.text', 'Input your friend\'s information below, and we\'ll send them an email after you complete your order to let them know you\'ve given them a gift subscription.')
            .should('contain.text', '12 month gift subscription$164 (you save $15)')
        cy.get('@commonForm')
            .find('[data-testid="maleGenderRadioButton"]')
            .find('input')
            .should('have.attr', 'checked')
        cy.get('@commonForm')
            .find('[data-testid="femaleGenderRadioButton"]')
            .should('be.visible')
        cy.get('@commonForm')
            .find('[data-testid="sendNowRadioButton"]')
            .find('input')
            .should('have.attr', 'checked')
        cy.get('@commonForm')
            .find('[data-testid="setDateRadioButton"]')
            .should('be.visible')
        cy.get('@commonForm')
            .find('[data-testid="nameInput"]')
            .type('Mary')
        cy.get('@commonForm')
            .find('[data-testid="emailInput"]')
            .type('test@gmail.com')
        cy.get('@commonForm')
            .find('[data-testid="messageInput"]')
            .type('text text text text')
        cy.get('@commonForm')
            .find('[data-testid="reviewOrderButton"]')
            .click()

        cy.title()
            .should('include', 'Log-in or Register to ScentBird Profile | Scentbird.com')
        cy.get('#mainContent > div._1JRfXr.QCqKGl')
            .should('contain.text', 'Log in to your account')
    })

    it('Check 6 months subscription scenario', () => {
        cy.get('#mainContent')
            .find('div.flex.flex-wrap._9hcI9q > div:nth-child(2)')
            .find('button > span')
            .click()
        cy.get('#trapfocus_6')
            .find('div.ml-36').as('commonForm')    
        cy.get('@commonForm')
            .should('contain.text', 'Ready to wrap it up?')
            .should('contain.text', 'Input your friend\'s information below, and we\'ll send them an email after you complete your order to let them know you\'ve given them a gift subscription.')
            .should('contain.text', '6 month gift subscription$84 (you save $6)')
        cy.get('@commonForm')
            .find('[data-testid="femaleGenderRadioButton"]')
            .click()
        cy.get('@commonForm')
            .find('[data-testid="sendNowRadioButton"]')
            .find('input')
            .should('have.attr', 'checked')
        cy.get('@commonForm')
            .find('[data-testid="setDateRadioButton"]')
            .should('be.visible')
        cy.get('@commonForm')
            .find('[data-testid="nameInput"]')
            .type('Mary')
        cy.get('@commonForm')
            .find('[data-testid="emailInput"]')
            .type('test@gmail.com')
        cy.get('@commonForm')
            .find('[data-testid="messageInput"]')
            .type('text text text text')
        cy.get('@commonForm')
            .find('[data-testid="reviewOrderButton"]')
            .click()

        cy.title()
            .should('include', 'Log-in or Register to ScentBird Profile | Scentbird.com')
        cy.get('#mainContent > div._1JRfXr.QCqKGl')
            .should('contain.text', 'Log in to your account')
    })

    it('Check 3 months subscription scenario', () => {
        cy.get('#mainContent')
            .find('div.flex.flex-wrap._9hcI9q > div:nth-child(3)')
            .find('button > span')
            .click()
        cy.get('#trapfocus_6')
            .find('div.ml-36').as('commonForm')    
        cy.get('@commonForm')
            .should('contain.text', 'Ready to wrap it up?')
            .should('contain.text', 'Input your friend\'s information below, and we\'ll send them an email after you complete your order to let them know you\'ve given them a gift subscription.')
            .should('contain.text', '3 month gift subscription$45')
        cy.get('@commonForm')
            .find('[data-testid="maleGenderRadioButton"]')
            .find('input')
            .should('have.attr', 'checked')
        cy.get('@commonForm')
            .find('[data-testid="setDateRadioButton"]')
            .click()
        
        cy.get('@commonForm')
            .find('[data-testid="nameInput"]')
            .type('Mary')
        cy.get('@commonForm')
            .find('[data-testid="emailInput"]')
            .type('test@gmail.com')
        cy.get('@commonForm')
            .find('[data-testid="messageInput"]')
            .type('text text text text')
        
        cy.get('@commonForm')
            .find('[data-testid="monthSelect"]')
            .find('select')
            .select('5')
        cy.get('@commonForm')
            .find('[data-testid="daySelect"]')
            .find('select')
            .select('15')
        cy.get('@commonForm')
            .find('[data-testid="yearSelect"]')
            .find('select')
            .select('2021')

        cy.get('@commonForm')
            .find('[data-testid="reviewOrderButton"]')
            .click()

        cy.title()
            .should('include', 'Log-in or Register to ScentBird Profile | Scentbird.com')
        cy.get('#mainContent > div._1JRfXr.QCqKGl')
            .should('contain.text', 'Log in to your account')
    })
})