describe('Scentbird gift page', () => {
    beforeEach(() => {
        cy.visit('/gift')
    })

    it('Check Gift Subscription page', () => {
        cy.title()
            .should('include', 'The Perfect Gift: Perfume Subscription Starting at $44 | Scentbird.com')
        cy.get('#mainContent')
            .find('div.text-white')
            .should('contain.text', 'Give a Gift Subscription')
        cy.get('#mainContent')
            .find('div.mt-12 > div')
            .should('contain.text', 'Because a Scentbird subscription is the gift that keeps on giving.')

        cy.get('#mainContent')
            .find('div.mt-60 > div')
            .should('contain.text', 'Here\'s how it works:')
        cy.get('#mainContent')
            .find('div.mt-60')
            .should('contain.text', 'Choose a plan')
            .should('contain.text', 'Choose whether to give your friend a 3 month subscription, 6 month subscription, or a 12 month subscription.')            
            .should('contain.text', 'Give your gift to a friend')
            .should('contain.text', 'Choose whether to give your friend a 3 month subscription, 6 month subscription, or a 12 month subscription.')
            .should('contain.text', 'Your friend gets in on the fun')
            .should('contain.text', 'Once your friend activates their subscription, they\'ll be able to explore our catalog of 600+ scents and discover new favorites every month.')
        
        cy.get('#mainContent')
            .find('div.mt-72')
            .find('div[role=list]')
            .should('contain.text', 'Authentic brands')
            .should('contain.text', 'Free shipping')
            .should('contain.text', 'Cancel anytime')
            .should('contain.text', 'No hidden fees')
    })

    it('Check Gift Subscription page cards list', () => {
        cy.get('#mainContent')
            .find('div.flex.flex-wrap._9hcI9q > div:nth-child(1)')
            .should('contain.text', '12 month gift subscription')
            .should('contain.text', '$164 (you save $15)')
            .should('contain.text', 'Free shipping to receiver')
            .should('contain.text', 'Silver case with their first delivery')
            .find('button > span')
            .should('contain.text', 'Continue')
        
        cy.get('#mainContent')
            .find('div.flex.flex-wrap._9hcI9q > div:nth-child(2)')
            .should('contain.text', '6 month gift subscription')
            .should('contain.text', '$84 (you save $6)')
            .should('contain.text', 'Free shipping to receiver')
            .should('contain.text', 'Silver case with their first delivery')
            .find('button > span')
            .should('contain.text', 'Continue')

        cy.get('#mainContent')
            .find('div.flex.flex-wrap._9hcI9q > div:nth-child(3)')
            .should('contain.text', '3 month gift subscription')
            .should('contain.text', '$45')
            .should('contain.text', 'Free shipping to receiver')
            .should('contain.text', 'Silver case with their first delivery')
            .find('button > span')
            .should('contain.text', 'Continue')
        })
})